name: Select Sports CI/CD Pipeline

on:
  push:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: ğŸ” Create .env file
        run: |
          touch .env
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env
          echo "OTP_EXPIRATION_MINUTES=${{ vars.OTP_EXPIRATION_MINUTES }}" >> .env
          echo "EMAIL_USER=${{ vars.EMAIL_USER }}" >> .env
          echo "EMAIL_PASSWORD=${{ vars.EMAIL_PASSWORD }}" >> .env
          echo "AUTH_SECRET=${{ vars.AUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}" >> .env
          echo "AUTH_TRUST_HOST=${{ vars.AUTH_TRUST_HOST }}" >> .env
          echo "NEXTAUTH_SECRET=${{ vars.NEXTAUTH_SECRET }}" >> .env
          echo "NEXT_PUBLIC_SITE_BACKEND_HOST=${{ vars.NEXT_PUBLIC_SITE_BACKEND_HOST }}" >> .env

      # - name: ğŸ— Build Next.js App
      #   run: yarn build

      # - name: ğŸ“¦ Compress build files
      #   run: tar -czf build.tar.gz ./

      - name: ğŸš€ Copy .env file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: "/home/ubuntu/select_sports"

      - name: ğŸ“‚ rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --progress --exclude=".git"
          path: ./*
          remote_path: /home/ubuntu/select_sports
          remote_host: ${{ secrets.EC2_DNS }}
          remote_user: ubuntu
          remote_key: '${{ secrets.SSH_PRIVATE_KEY }}'
      
      - name: SSH into EC2 and Install Dependencies, Build & Restart App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            which yarn
            which pm2
            cd /home/ubuntu/select_sports
            yarn install --frozen-lockfile
            yarn build
            pm2 restart all || pm2 start yarn --name "select_sports" -- start -p 3005
            pm2 save

    # - name: ğŸ“‚ Extract and restart app on EC2
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ubuntu
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /var/www/select_sports
    #       tar -xzf build.tar.gz
    #       rm -f build.tar.gz
    #       npm i -g pm2
    #       pm2 restart all || pm2 start yarn --name "select_sports" -- start
    #       pm2 save
