# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
    - name: ðŸ“‚ Set working directory
      run: cd select_sports
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: ðŸ›  Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: select_sports
    - name: Set DATABASE_URL from GitHub Secret
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: yarn run build
      working-directory: select_sports
    - name: ðŸ“‚ rsync deployments
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: ./*
        remote_path: /var/www/html/select_sports/
        remote_host: https://13.127.122.36/
        remote_user: ubuntu
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
    # - run: npm test
